# Generated by Django 4.2.3 on 2023-07-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyecto', '0002_alter_consulta_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
