# Generated by Django 4.2.3 on 2023-07-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyecto', '0003_alter_consulta_codigo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consulta',
            table='consultas_table',
        ),
    ]
